version: "3"

services:
  app: 
    image: laravel-app
    container_name: laravel-app
    build: 
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mysql
      - redis
    env_file:
      - .docker.env
    environment: 
      CONTAINER_ROLE: app
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
  scheduler:
    image: laravel-app
    container_name: laravel-scheduler
    depends_on:
      - app
      - mysql 
      - redis
    env_file:
      - .docker.env
    environment: 
      CONTAINER_ROLE: scheduler
    volumes:
      - .:/var/www/html
  queue:
    image: laravel-app
    container_name: laravel-queue
    depends_on:
      - app
      - mysql 
      - redis
    env_file:
      - .docker.env
    environment: 
      CONTAINER_ROLE: queue
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - 33061:3306
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:4-alpine
    container_name: laravel-redis
    ports:
      - 63791:6379
    volumes:
      - redis:/data

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
  
      
